name: jlabtutorial
channels:
  - anaconda
dependencies:
  - python
  - numpy
  - pip
  - matplotlib
  - ipython=7.10.0
  - mordred
  - numpy
  - pandas
  - rdkit=2019.09.2
  - jupyterlab_3dmol
  - py3Dmol
  - pip:
    - scikit-learn==0.22
    - ipymol

